"""PDF generation utilities for ResearchPilot AI reports.

Converts a markdown intelligence report into a styled PDF file using
markdown2 for markdown→HTML conversion and xhtml2pdf for HTML→PDF rendering.
"""

import os
from datetime import datetime

import markdown2
from xhtml2pdf import pisa


REPORTS_DIR = "reports"


def generate_pdf(report_text: str, research_goal: str) -> str:
    """Convert a markdown report to a styled PDF and save it to disk.

    Args:
        report_text:   The full intelligence report in markdown format.
        research_goal: The original research question (used in the header).

    Returns:
        The absolute path of the generated PDF file.
    """
    # Ensure the output directory exists.
    os.makedirs(REPORTS_DIR, exist_ok=True)

    # Generate a unique filename based on the current timestamp.
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = os.path.join(REPORTS_DIR, f"research_report_{timestamp}.pdf")

    # Convert markdown to HTML with table and fenced-code-block support.
    body_html = markdown2.markdown(
        report_text,
        extras=["tables", "fenced-code-blocks"],
    )

    current_datetime = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Build the complete styled HTML document.
    full_html = f"""
<html>
<head>
  <meta charset="utf-8">
  <style>
    body {{
      font-family: Arial;
      font-size: 12px;
      margin: 40px;
      color: #1a1a1a;
    }}
    h1 {{
      color: #1a237e;
      font-size: 24px;
      border-bottom: 3px solid #1a237e;
      padding-bottom: 8px;
    }}
    h2 {{
      color: #283593;
      font-size: 18px;
      margin-top: 24px;
      border-left: 4px solid #3949ab;
      padding-left: 10px;
    }}
    h3 {{
      color: #303f9f;
      font-size: 14px;
    }}
    p {{
      line-height: 1.7;
      margin: 8px 0;
    }}
    li {{
      line-height: 1.7;
    }}
    strong {{
      color: #1a237e;
    }}
    .header {{
      background: #1a237e;
      color: white;
      padding: 20px;
      margin-bottom: 30px;
      border-radius: 4px;
    }}
    .header h1 {{
      color: white;
      border-bottom: none;
      margin: 0 0 8px 0;
    }}
    .header p {{
      margin: 4px 0;
      color: white;
    }}
    .footer {{
      margin-top: 40px;
      padding-top: 10px;
      border-top: 1px solid #ccc;
      font-size: 10px;
      color: #666;
      text-align: center;
    }}
    table {{
      border-collapse: collapse;
      width: 100%;
    }}
    td, th {{
      border: 1px solid #ddd;
      padding: 8px;
      text-align: left;
    }}
    th {{
      background: #1a237e;
      color: white;
    }}
  </style>
</head>
<body>
  <div class="header">
    <h1>ResearchPilot AI</h1>
    <p>Intelligence Report</p>
    <p>Research Goal: {research_goal}</p>
    <p>Generated: {current_datetime}</p>
  </div>
  {body_html}
  <div class="footer">
    <p>Generated by ResearchPilot AI | Confidential</p>
  </div>
</body>
</html>
"""

    # Render HTML to PDF using xhtml2pdf.
    with open(filename, "wb") as pdf_file:
        pisa.CreatePDF(full_html, dest=pdf_file)

    return os.path.abspath(filename)


def get_report_path(filename: str) -> str:
    """Return the absolute path of a report file stored in the reports directory.

    Args:
        filename: The bare filename (e.g. "research_report_20260101_120000.pdf").

    Returns:
        The absolute path to the file.
    """
    return os.path.abspath(os.path.join(REPORTS_DIR, filename))


if __name__ == "__main__":
    test_report = (
        "# Test Report\n"
        "## Summary\n"
        "This is a **test** report.\n"
        "## Findings\n"
        "- Point one\n"
        "- Point two\n"
        "| Column A | Column B |\n"
        "|----------|----------|\n"
        "| Value 1  | Value 2  |"
    )
    path = generate_pdf(test_report, "Test Research Goal")
    print(f"PDF generated at: {path}")